// Libs
extern crate proc_macro;
use proc_macro::TokenStream;
use quote::quote;
use syn;

// Module


#[proc_macro_attribute]
pub fn launch(_attr: TokenStream, item: TokenStream) -> TokenStream {
    // We want to start the server here.
    // This call should have a macro that contains all the necessary information to start all the
    // sockets
    let input: syn::ItemFn = syn::parse(item).unwrap();
    let function_name = input.sig.ident;
    let stmts = input.block.stmts;
    quote!(
        // This function will be the client handler.
        // It is game specific. Shared features should be general and generated by macro
        fn #function_name() {
            #(#stmts)*
        }

        fn main() {
            
            #function_name();
        }
    ).into()
}

